# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.finchp.com
title: Projet Finch
email: info@finchp.com
author: Projet Finch
description: "Des capsules d'apprentissage en ligne pratiques, courtes et efficaces sur le numérique et les nouvelles pratiques d'affaires."
copyright: 'Copyright &copy; 2016 Projet Finch. Tous droits réservés.'
exclude: [_tools]

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/finchproj
  - title: facebook
    url: https://www.facebook.com/ProjetFinch
