# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.finchp.com
title: Projet Finch
email: info@finchp.com
author: Projet Finch
description: "Projet Finch. Centre d'apprentissage en ligne des organisations qui savent s'adapter. @finchproj ou www.FinchP.com."
copyright: 'Copyright &copy; 2016 Projet Finch. Tous droits réservés.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/finchproj
  - title: facebook
    url: https://www.facebook.com/ProjetFinch
